############################################################
# Minimal Java logger configuration
############################################################
.level = INFO
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.SimpleFormatter.format=%5$s%n
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
DLMLLocal.level = OFF
ProtocolThread.level = OFF
